#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

if [ "$(uname -s)" == "Darwin" ]; then
	# Run Homebrew through the Brewfile
	echo "› brew bundle"
	brew bundle

else
	echo "> apt-get install"
	sudo apt-get install -y $(cat Aptfile)
fi


while read gemname; do
  if [ "$(uname -s)" == "Darwin" ]; then
  	brew gem info $gemname > /dev/null 2>&1 || brew gem install $gemname
  else
  	sudo gem info $gemname > /dev/null 2>&1 || gem install $gemname
  fi
done < "ruby/global.gems"


# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
